# @package _global_.dataset
path: /home/d32485/forecasting_benchmark/data/cer_bis/load_curve.parquet
path_client_split: /home/d32485/forecasting_benchmark/data/cer_bis/train_valid_test_id_split.pkl
timestamp_col: "time"
layout: "wide"

context_length: 512
prediction_length: 96
stride: 96

name: "cer_bis"
