defaults:
  - dataset: cer_bis
  - model: statistical
  - _self_

output_dir: "outputs/statistical"

hydra:
  run:
    dir: outputs/statistical/${dataset.name}/max_lookback_${model.max_lookback}/${now:%Y-%m-%d_%H-%M-%S}
