defaults:
  - dataset: cer_bis
  - model: chronos
  - _self_

output_dir: "outputs/chronos2"

hydra:
  run:
    dir: outputs/chronos2/${dataset.name}/ctx${dataset.context_length}_h${dataset.prediction_length}/${now:%Y-%m-%d_%H-%M-%S}
