defaults:
  - dataset: cer_bis
  - model: chronos     #chronos | tsicl | <nouveau>
  - _self_

output_dir: "."
hydra:
  run:
    dir: outputs/${model.name}/${dataset.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: outputs/${model.name}/${dataset.name}/multirun_${now:%Y-%m-%d_%H-%M-%S}
    subdir: ctx${dataset.context_length}_h${dataset.prediction_length}