defaults:
  - dataset: cer
  - model: patchtst_fm
  - _self_

output_dir: "outputs/patchtst_fm"

hydra:
  run:
    dir: outputs/patchtst_fm/${dataset.name}/ctx${dataset.context_length}_pred${dataset.prediction_length}/${now:%Y-%m-%d_%H-%M-%S} 